version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytest
    versions:
    - ">= 6.2.a, < 6.3"
  - dependency-name: black
    versions:
    - 21.4b0
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.11.0
    - 2.12.0
  - dependency-name: tox
    versions:
    - 3.21.2
    - 3.21.3
    - 3.21.4
  - dependency-name: django
    versions:
    - 3.1.6
